---
services:
  plex:
    container_name: plex
    image: lscr.io/linuxserver/plex:latest
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - VERSION=docker
    volumes:
      - ${ROOT}/mediaserver/config/plex/db:/config
      - ${ROOT}/mediaserver/config/plex/transcode:/transcode
      - ${HDDSTORAGE}/media/tvshows:/tvshows
      - ${HDDSTORAGE}/media/movies:/movies
      - ${HDDSTORAGE}/media/music:/music
    restart: unless-stopped

  sonarr:
    container_name: sonarr
    image: lscr.io/linuxserver/sonarr:latest
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${ROOT}/mediaserver/config/sonarr:/config
      - ${HDDSTORAGE}/media/tvshows:/tvshows
      - ${HDDSTORAGE}/downloads:/downloads
      - ${HDDSTORAGE}/downloads/recycle:/recycle
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    container_name: radarr
    image: lscr.io/linuxserver/radarr:latest
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${ROOT}/mediaserver/config/radarr:/config
      - ${HDDSTORAGE}/media/movies:/movies
      - ${HDDSTORAGE}/downloads:/downloads
      - ${HDDSTORAGE}/downloads/recycle:/recycle
    ports:
      - 7878:7878
    restart: unless-stopped

  bazarr:
    container_name: bazarr
    image: lscr.io/linuxserver/bazarr:latest
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${ROOT}/mediaserver/config/bazarr:/config
      - ${HDDSTORAGE}/media/movies:/movies 
      - ${HDDSTORAGE}/media/tvshows:/tvshows 
    ports:
      - 6767:6767
    restart: unless-stopped    

  overseerr:
    container_name: overseerr
    image: sctx/overseerr:latest
    environment:
      - LOG_LEVEL=debug
      - TZ=${TZ}
    ports:
      - 5055:5055
    volumes:
      - ${ROOT}/mediaserver/config/overseerr:/app/config
    restart: unless-stopped

  agent:
    container_name: portainer_agent
    image: portainer/agent:latest
    ports:
      - 9001:9001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    restart: always