---
services:
  plex:
    container_name: plex
    image: lscr.io/linuxserver/plex:latest
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - VERSION=docker
    volumes:
      - ${ROOT}/mediaserver/config/plex/db:/config
      - ${ROOT}/mediaserver/config/plex/transcode:/transcode
      - ${HDDSTORAGE}/media/tvshows:/tvshows
      - ${HDDSTORAGE}/media/movies:/movies
      - ${HDDSTORAGE}/media/music:/music
      - ${HDDSTORAGE}/media/anime:/anime
    restart: unless-stopped


  agent:
    container_name: portainer_agent
    image: portainer/agent:latest
    ports:
      - 9001:9001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    restart: always