---
services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${ROOT}/utilityserver/config/heimdall:/config
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      TZ: ${TZ}
      WATCHTOWER_SCHEDULE: 0 30 3 * * 6
      WATCHTOWER_MONITOR_ONLY: "false"
      WATCHTOWER_ROLLING_RESTART: "true"
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_NO_STARTUP_MESSAGE: "true"
      WATCHTOWER_NOTIFICATIONS: "shoutrrr"
      WATCHTOWER_NOTIFICATION_URL: "discord://${DISTOKEN}@${DISWEBHOOKID}"
    restart: unless-stopped
      
  librespeed:
    container_name: librespeed
    image: lscr.io/linuxserver/librespeed:latest
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - PASSWORD=${LIBREPASSWORD}
    volumes:
      - ${ROOT}/utilityserver/config/librespeed:/config
    ports:
      - 8080:80
    restart: unless-stopped

  smokeping:
    container_name: smokeping
    image: lscr.io/linuxserver/smokeping:latest
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${ROOT}/utilityserver/config/smokeping:/config
      - ${ROOT}/utilityserver/config/smokeping/data:/data
    ports:
      - 8088:80
    restart: unless-stopped

  bookstack:
    container_name: bookstack
    image: lscr.io/linuxserver/bookstack
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - APP_URL=http://192.168.1.40:6875
      - DB_HOST=bookstack_db
      - DB_PORT=3306
      - DB_USER=bookstack
      - DB_PASS=${DBPASS}
      - DB_DATABASE=bookstackapp
    volumes:
      - ${ROOT}/utilityserver/config/bookstack_app_data:/config
    ports:
      - 6875:80
    restart: unless-stopped
    depends_on:
      - bookstack_db
      
  bookstack_db:
    image: lscr.io/linuxserver/mariadb
    container_name: bookstack_db
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - MYSQL_ROOT_PASSWORD=${DBPASS}
      - TZ=${TZ}
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=${DBPASS}
    volumes:
      - ${ROOT}/utilityserver/config/bookstack_db_data:/config
    restart: unless-stopped

  # omada_controller:
  #   image: mbentley/omada-controller:latest
  #   container_name: omada_controller
  #   environment:
  #     - PUID=${PUID}
  #     - PGID=${PGID}
  #     - TZ=${TZ}
  #     - MANAGE_HTTP_PORT=8088
  #     - MANAGE_HTTPS_PORT=8043
  #     - PORTAL_HTTP_PORT=8088
  #     - PORTAL_HTTPS_PORT=8043
  #     - SHOW_SERVER_LOGS=true
  #     - SHOW_MONGODB_LOGS=false
  #   ports:
  #     - 8089:8088
  #     - 8043:8043
  #   volumes:
  #     - ${ROOT}/utilityserver/config/omada/data:/opt/tplink/EAPController/data
  #     - ${ROOT}/utilityserver/config/omada/logs:/opt/tplink/EAPController/logs
  #   restart: unless-stopped

  actualbudget:
    image: actualbudget/actual-server:latest
    container_name: actualbudget
    ports:
      - 5006:5006
    volumes:
      - ${ROOT}/utilityserver/config/actual:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.actual.rule=Host(`actualbudget.${DNSNAME}`)"
      - "traefik.http.routers.actual.entrypoints=websecure"
      - "traefik.http.services.actual.loadbalancer.server.port=5006"
    networks:
      - traefik-local
    restart: unless-stopped

  traefik:
    container_name: traefikgen
    image: traefik:latest
    volumes:
      - ${ROOT}/vaultserver/config/traefikgen/letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 80:80
      - 443:443
    environment:
      - CF_API_EMAIL=${CF_EMAIL}
      - CF_DNS_API_TOKEN=${CF_APIKEY}
    command:
      - --log.level=DEBUG
      - --api.dashboard=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      # Set up LetsEncrypt
      - --certificatesresolvers.letsencrypt.acme.dnschallenge=true
      - --certificatesresolvers.letsencrypt.acme.dnschallenge.provider=cloudflare
      - --certificatesresolvers.letsencrypt.acme.dnschallenge.delayBeforeCheck=20
      - --certificatesresolvers.letsencrypt.acme.dnschallenge.resolvers=1.1.1.1:53
      - --certificatesresolvers.letsencrypt.acme.dnschallenge.resolvers=1.0.0.1:53
      - --certificatesresolvers.letsencrypt.acme.email=${CF_EMAIL}
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
      # - --certificatesresolvers.letsencrypt.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
      # Set up an insecure listener that redirects all traffic to TLS      
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      # Set up the TLS configuration for our websecure listener
      - --entrypoints.websecure.http.tls=true
      - --entrypoints.websecure.http.tls.certResolver=letsencrypt
      - --entrypoints.websecure.http.tls.domains[0].main=${DNSNAME}
      - --entrypoints.websecure.http.tls.domains[0].sans=*.${DNSNAME}
    networks:
      - traefik-local
    labels:
      - traefik.enable=true
      - traefik.http.routers.dashboard.rule=Host(`traefikgen.${DNSNAME}`)
      - traefik.http.routers.dashboard.entrypoints=websecure
      - traefik.http.routers.dashboard.service=api@internal
    restart: unless-stopped


  portainer-ce:
    container_name: portainer
    image: portainer/portainer-ce:latest
    ports:
      - 8000:8000
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: always

volumes:
  portainer_data:

networks:
  traefik-local:
    external: true


