---
services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${ROOT}/utilityserver/config/heimdall:/config
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      TZ: ${TZ}
      WATCHTOWER_SCHEDULE: 0 30 3 * * 6
      WATCHTOWER_MONITOR_ONLY: "false"
      WATCHTOWER_ROLLING_RESTART: "true"
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_NO_STARTUP_MESSAGE: "true"
      WATCHTOWER_NOTIFICATIONS: "shoutrrr"
      WATCHTOWER_NOTIFICATION_URL: "discord://${DISTOKEN}@${DISWEBHOOKID}"
    restart: unless-stopped
      
  librespeed:
    container_name: librespeed
    image: lscr.io/linuxserver/librespeed:latest
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - PASSWORD=${LIBREPASSWORD}
    volumes:
      - ${ROOT}/utilityserver/config/librespeed:/config
    ports:
      - 8080:80
    restart: unless-stopped

  smokeping:
    container_name: smokeping
    image: lscr.io/linuxserver/smokeping:latest
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${ROOT}/utilityserver/config/smokeping:/config
      - ${ROOT}/utilityserver/config/smokeping/data:/data
    ports:
      - 8088:80
    restart: unless-stopped

  bookstack:
    container_name: bookstack
    image: lscr.io/linuxserver/bookstack
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - APP_URL=http://192.168.1.40:6875
      - DB_HOST=bookstack_db
      - DB_PORT=3306
      - DB_USER=bookstack
      - DB_PASS=${DBPASS}
      - DB_DATABASE=bookstackapp
    volumes:
      - ${ROOT}/utilityserver/config/bookstack_app_data:/config
    ports:
      - 6875:80
    restart: unless-stopped
    depends_on:
      - bookstack_db
      
  bookstack_db:
    image: lscr.io/linuxserver/mariadb
    container_name: bookstack_db
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - MYSQL_ROOT_PASSWORD=${DBPASS}
      - TZ=${TZ}
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=${DBPASS}
    volumes:
      - ${ROOT}/utilityserver/config/bookstack_db_data:/config
    restart: unless-stopped

  home_assistant:
    image: lscr.io/linuxserver/homeassistant:latest
    container_name: home_assistant
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - 8123:8123
    volumes:
      - ${ROOT}/utilityserver/config/homeassistant:/config
    restart: unless-stopped

  portainer-ce:
    container_name: portainer
    image: portainer/portainer-ce:latest
    ports:
      - 8000:8000
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: always

volumes:
  portainer_data:



