---
services:
  vpn:
    container_name: vpn
    image: dperson/openvpn-client:latest
    environment:
      - OTHER_ARGS= --mute-replay-warnings
    cap_add:
      - net_admin
      - SYS_MODULE
    restart: unless-stopped
    volumes:
      - ${ROOT}/vpnserver/config/vpn:/vpn
      - /lib/modules:/lib/modules
    security_opt:
      - label:disable
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8112:8112 #deluge web UI Port
      - 9696:9696 #prowlarr port
      # - 9091:9091 #transmission
      # - 51413:51413 #transmission
      # - 51413:51413/udp #transmission udp
    command: '-f "" -r 192.168.1.0/24' # this is your local subnet to be able to communicate to sonarr/radarr

  deluge:
    container_name: deluge
    image: linuxserver/deluge:latest
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${ROOT}/vpnserver/config/deluge:/config
      - ${ROOT}/vpnserver/config/deluge/watch:/watch
      - ${HDDSTORAGE}/downloads:/downloads
    network_mode: 'service:vpn' 
    depends_on:                 
      - vpn                     

  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:latest
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${ROOT}/vpnserver/config/prowlarr:/config
    restart: unless-stopped
    network_mode: 'service:vpn' 
    depends_on:                 
      - vpn                     

  # transmission:
  #   container_name: transmission
  #   image: lscr.io/linuxserver/transmission:latest
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=Europe/Madrid
  #   volumes:
  #     - ${ROOT}/vpnserver/config/transmission:/config
  #     - ${ROOT}/vpnserver/config/transmission/watch:/watch
  #     - ${HDDSTORAGE}/downloads:/downloads
  #   restart: unless-stopped
  #   network_mode: 'service:vpn'
  #   depends_on:
  #     - vpn

  agent:
    image: portainer/agent:latest
    container_name: portainer_agent
    ports:
      - 9001:9001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    restart: always