version: "1"
services:
  vpn:
    container_name: vpn
    image: 'dperson/openvpn-client:latest'
    environment:
      - 'OTHER_ARGS= --mute-replay-warnings'
    cap_add:
      - net_admin
      - SYS_MODULE
    restart: unless-stopped
    volumes:
      - /home/death/vpnserver/config/vpn:/vpn
      - /lib/modules:/lib/modules
    security_opt:
      - 'label:disable'
    devices:
      - '/dev/net/tun:/dev/net/tun'
    ports:
      - '8112:8112' #deluge web UI Port
    command: '-f "" -r 192.168.68.0/24'

  deluge:
    container_name: deluge
    image: 'linuxserver/deluge:latest'
    restart: unless-stopped
    environment:
      - PUID=1001
      - PGID=1002
      - TZ=America/Los_Angeles
    volumes:
      - /home/death/vpnserver/config/deluge:/config'
      - /mnt/data/downloads:/downloads
    #ports:
    #  - '8112:8112' #uncomment if you are not using the VPN
    network_mode: 'service:vpn' #comment/remove if you are not using the VPN
    depends_on:                 #comment/remove if you are not using the VPN
      - vpn                     #comment/remove if you are not using the VPN