---
services:
  traefik:
    container_name: traefik
    image: traefik:latest
    volumes:
      - ${ROOT}/vaultserver/config/traefik/letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    environment:
      - CF_API_EMAIL=${CF_EMAIL}
      - CF_DNS_API_TOKEN=${CF_APIKEY}
    command:
      - --log.level=DEBUG
      - --api.dashboard=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      # Set up LetsEncrypt
      - --certificatesresolvers.letsencrypt.acme.dnschallenge=true
      - --certificatesresolvers.letsencrypt.acme.dnschallenge.provider=cloudflare
      - --certificatesresolvers.letsencrypt.acme.dnschallenge.delayBeforeCheck=20
      - --certificatesresolvers.letsencrypt.acme.dnschallenge.resolvers=1.1.1.1:53
      - --certificatesresolvers.letsencrypt.acme.dnschallenge.resolvers=1.0.0.1:53
      - --certificatesresolvers.letsencrypt.acme.email=${CF_EMAIL}
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
      # - --certificatesresolvers.letsencrypt.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
      # Set up an insecure listener that redirects all traffic to TLS      
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      # Set up the TLS configuration for our websecure listener
      - --entrypoints.websecure.http.tls=true
      - --entrypoints.websecure.http.tls.certResolver=letsencrypt
      - --entrypoints.websecure.http.tls.domains[0].main=${DNSNAME}
      - --entrypoints.websecure.http.tls.domains[0].sans=*.${DNSNAME}
    networks:
      - internal
      - default

  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server:latest
    depends_on:
      - traefik
    env_file:
      - vaultwarden-var.env
    volumes:
      - ${ROOT}/vaultserver/config/vaultwarden:/data
    restart: always
    networks:
      - internal
    labels:
      - traefik.enable=true
      - traefik.http.routers.vaultwarden.rule=Host(`vault.${DNSNAME}`)
      - traefik.http.routers.vaultwarden.entrypoints=websecure


  agent:
    container_name: portainer_agent
    image: portainer/agent:latest
    ports:
      - 9001:9001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - default
    restart: always
  
networks:
  internal:
    name: internal_test
    external: true
