---
services:
  # traefik:
  #   container_name: traefik
  #   image: traefik:latest
  #   volumes:
  #     - ${ROOT}/vaultserver/config/traefik/letsencrypt:/letsencrypt
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #   ports:
  #     - 80:80
  #     - 443:443
  #   environment:
  #     - CLOUDFLARE_EMAIL=${CF_EMAIL}
  #     - CLOUDFLARE_API_KEY=${CF_APIKEY}
  #   command:
  #     - --log.level=DEBUG
  #     - --providers.docker=true
  #     - --providers.docker.exposedbydefault=false
  #     - --entrypoints.web.address=:80
  #     - --entrypoints.web.http.redirections.entryPoint.to=websecure
  #     - --entrypoints.web.http.redirections.entryPoint.scheme=https
  #     - --entrypoints.websecure.address=:443
  #     - --certificatesresolvers.cloudflare.acme.dnschallenge=true
  #     - --certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare
  #     - --certificatesresolvers.cloudflare.acme.email=${CF_EMAIL}
  #     - --certificatesresolvers.cloudflare.acme.storage=/letsencrypt/acme.json
  #     # - --certificatesresolvers.cloudflare.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
    
  # nginx:
  #   container_name: nginx-test
  #   image: nginx
  #   labels:
  #     - traefik.enable=true
  #     - traefik.http.routers.nginx.rule=Host(`testtest.${DNSNAME}`)
  #     - traefik.http.routers.nginx.tls.certresolver=cloudflare
  #     - traefik.http.routers.nginx.entrypoints=websecure

  
  # traefik:
  #   image: "traefik:v2.11"
  #   container_name: "traefik"
  #   command:
  #     #- "--log.level=DEBUG"
  #     - "--api.insecure=true"
  #     - "--providers.docker=true"
  #     - "--providers.docker.exposedbydefault=false"
  #     - "--entrypoints.web.address=:80"
  #   ports:
  #     - "80:80"
  #     - "8080:8080"
  #   volumes:
  #     - "/var/run/docker.sock:/var/run/docker.sock:ro"

  whoami:
    image: "traefik/whoami"
    container_name: "simple-service"
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.whoami.rule=Host(`whoami.${DNSNAME}`)"
    #   - "traefik.http.routers.whoami.entrypoints=web"

  agent:
    container_name: portainer_agent
    image: portainer/agent:latest
    ports:
      - 9001:9001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    restart: always