# file: playbooks/pihole.yml
- name: Managing Pihole Host
  gather_facts: yes      # Gather system facts about the hosts
  hosts: pihole          # This matches [pihole] in production/hosts
  become: yes            # Become SUDO
  roles:
    - role: common